# Generated by Django 3.1.4 on 2020-12-02 16:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('farm_loc', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Insert genre!', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('summary', models.TextField(help_text='Enter a brief description of the product', max_length=1000)),
                ('farmer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='piantala.farmer')),
                ('genre', models.ManyToManyField(help_text='Select a genre for this product', to='piantala.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular product across istances', primary_key=True, serialize=False)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(blank=True, choices=[('d', 'Disponibile'), ('p', 'Prenotabile'), ('r', 'Riservato'), ('e', 'Esaurito')], default='d', help_text='Product availability', max_length=1)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='piantala.product')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
    ]
