# Generated by Django 3.1.4 on 2020-12-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piantala', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='image',
            field=models.ImageField(default='', upload_to='profile_image'),
        ),
    ]
