# Generated by Django 3.1.4 on 2020-12-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piantala', '0002_auto_20201202_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=models.IntegerField(max_length=15),
        ),
    ]
