# Generated by Django 3.1.4 on 2020-12-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piantala', '0003_auto_20201214_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='image',
            field=models.ImageField(blank=True, default='/static/images/favicon.ico', null=True, upload_to='profile_image'),
        ),
    ]
