# Generated by Django 3.1.4 on 2020-12-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piantala', '0004_auto_20201202_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinstance',
            name='location',
        ),
    ]
