# Generated by Django 3.1.4 on 2020-12-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piantala', '0005_remove_productinstance_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinstance',
            options={},
        ),
        migrations.RemoveField(
            model_name='productinstance',
            name='due_back',
        ),
    ]
