# Generated by Django 3.1.4 on 2020-12-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piantala', '0007_auto_20201211_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='piantala/images'),
        ),
    ]
