# Generated by Django 3.1.2 on 2020-12-12 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('piantala', '0010_auto_20201211_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='avatar')),
                ('indirizzo', models.CharField(default='', max_length=50)),
                ('città', models.CharField(default='', max_length=50)),
                ('CAP', models.IntegerField(default='')),
                ('telefono', models.IntegerField(default='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
