# Generated by Django 3.1.4 on 2020-12-13 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piantala', '0011_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
