# Generated by Django 3.1.4 on 2020-12-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piantala', '0013_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
