# Generated by Django 3.1.4 on 2020-12-02 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piantala', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookInstance',
            new_name='ProductInstance',
        ),
    ]
